In [1]:
import numpy as np

In [28]:
import numpy as np
def spiral(n):
  matrix = np.array([[0]*n for _ in range(n)])
  top, bottom = 0,n-1
  left, right = 0,n-1
  num = 1

  while top<=bottom and left <=right:

    for i in range(left,right+1):
      matrix[top][i] = num
      num+=1
    top+=1

    for i in range(top, bottom+1):
      matrix[i][right] = num
      num+=1
    right-=1

    for i in range(right,left-1,-1):
      matrix[bottom][i] = num
      num+=1
    bottom-=1

    for i in range(bottom, top-1,-1):
      matrix[i][left] = num
      num+=1
    left+=1

  return matrix
spiral(4)

In [29]:
spiral(4)

array([[ 1,  2,  3,  4],
       [12, 13, 14,  5],
       [11, 16, 15,  6],
       [10,  9,  8,  7]])

In [25]:
spiral(5)

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19,  6],
       [15, 24, 25, 20,  7],
       [14, 23, 22, 21,  8],
       [13, 12, 11, 10,  9]])

In [26]:
spiral(3)

array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])

In [27]:
spiral(6)

array([[ 1,  2,  3,  4,  5,  6],
       [20, 21, 22, 23, 24,  7],
       [19, 32, 33, 34, 25,  8],
       [18, 31, 36, 35, 26,  9],
       [17, 30, 29, 28, 27, 10],
       [16, 15, 14, 13, 12, 11]])